spring.application.name=Report_Service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=2007FuaD0217@

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

report.storage.path=reports/